### PR TITLE
test github actions

### PR DESCRIPTION
**Pull request by james-ftp**

### CODE REVIEW

**Comment by james-ftp** [comment]
tasty @smills2929 @lowaa the 5 minute setup/demo of this is pretty shiny

**Comment by smills2929** [comment]
This is pretty cool!

**Review by lowaa — APPROVED** [review]
sure 👍

**Comment by lowaa** [comment]
@james-ftp im just going over some old PRs - this one is still good to go ?

**Comment by james-ftp** [comment]
oops sorry @lowaa this should actually be closed

**Pull request closed without merging**
